export const dummyData = {
    articles: [
      {
        source: { id: "bbc-news", name: "BBC News" },
        author: "John Doe",
        title: "Global Economic Outlook for 2025",
        description: "Experts predict a challenging economic landscape in 2025, but innovation and green technologies may offer hope.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "business",
        publishedAt: "2025-01-13T10:00:00Z",
      },
      {
        source: { id: "cnn", name: "CNN" },
        author: "Jane Smith",
        title: "Tech Giants to Face Tougher Regulations",
        description: "With increasing concerns over data privacy, governments worldwide are stepping up their efforts to regulate big tech.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "technology",
        publishedAt: "2025-01-12T09:30:00Z",
      },
      {
        source: { id: "the-guardian", name: "The Guardian" },
        author: "Alex Brown",
        title: "Climate Change: The Next Decade",
        description: "The next decade will be critical in determining the future of our planet, as experts warn of rising temperatures and extreme weather events.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "environment",
        publishedAt: "2025-01-11T15:45:00Z",
      },
      {
        source: { id: "bbc-news", name: "BBC News" },
        author: "Samuel Davis",
        title: "Artificial Intelligence: Revolutionizing Healthcare",
        description: "AI is set to transform healthcare by improving diagnostics, treatment options, and patient care.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "technology",
        publishedAt: "2025-01-10T13:00:00Z",
      },
      {
        source: { id: "cnn", name: "CNN" },
        author: "Emma Harris",
        title: "Tokyo 2025 Olympics: Preparing for a New Era",
        description: "With a focus on sustainability and innovation, the upcoming 2025 Olympics promises to be a game-changer for global sports.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "sports",
        publishedAt: "2025-01-09T08:45:00Z",
      },
      {
        source: { id: "the-guardian", name: "The Guardian" },
        author: "George Smith",
        title: "Global Trade Shifts Amid Political Tensions",
        description: "As tensions rise between major global players, international trade agreements are undergoing significant changes.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "business",
        publishedAt: "2025-01-08T14:20:00Z",
      },
      {
        source: { id: "bbc-news", name: "BBC News" },
        author: "Lily Adams",
        title: "How Remote Work Is Changing Cities",
        description: "The rise of remote work is reshaping urban areas, as more people relocate to smaller cities and rural regions.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "business",
        publishedAt: "2025-01-07T16:35:00Z",
      },
      {
        source: { id: "cnn", name: "CNN" },
        author: "Carlos Mendoza",
        title: "NASA's New Mission to Mars: What We Know",
        description: "NASA's upcoming mission to Mars promises groundbreaking discoveries about the planet's history and potential for future human habitation.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "science",
        publishedAt: "2025-01-06T12:15:00Z",
      },
      {
        source: { id: "the-guardian", name: "The Guardian" },
        author: "Sophia White",
        title: "Electric Cars: The Road Ahead",
        description: "The electric car revolution is accelerating, with more automakers committing to fully electric lineups by the end of the decade.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "technology",
        publishedAt: "2025-01-05T11:00:00Z",
      },
      {
        source: { id: "bbc-news", name: "BBC News" },
        author: "John Taylor",
        title: "The Future of Food: Innovations in Agriculture",
        description: "Agricultural innovations like vertical farming and lab-grown meat are set to revolutionize the way we grow and consume food.",
        url: "https://www.bbc.com/sport/tennis/articles/cde9nrlwpk7o",
        category: "environment",
        publishedAt: "2025-01-04T13:00:00Z",
      },
    ],
  };